apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: simple-time-app
    role: web
  ports:
    - name: http
      port: 8080
      targetPort: timeapp
  type: LoadBalancer
