web:
  replicas: 2
  image: 891126569531.dkr.ecr.eu-west-1.amazonaws.com/fdvieira/timeapp
  tag: "1.0"
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
